# Theme Settings
minimal_mistakes_skin: "contrast" # Other options: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Site Settings
locale: "en-US"
rtl: false
title: "My Online Portfolio"
title_separator: "-"
subtitle: "Customer Service Manager & IT Professional"
name: "Leesa Moore"
description: "Explore my work, accomplishments, and career journey. Featuring a detailed resume and professional expertise."
url: "https://leeeeesamo.github.io/leeeeesamo.resume/" # Your live GitHub Pages URL
baseurl: "" # Leave blank for root domain
repository: "leeeeesamo/leeeeesamo.resume" # GitHub repository
teaser: "/assets/images/portfolio-thumbnail.jpg" # Path to your OG image or default thumbnail
logo: "/assets/images/logo.png" # Path to your logo
masthead_title: "Leesa Moore - Online Portfolio" # Displays as the main title in the masthead
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Leesa Moore"
copyright_url: "https://leeeeesamo.github.io"

# Header 
header:
  image: /assets/images/header.jpg
  
# Social Sharing
og_image: "/assets/images/portfolio-thumbnail.jpg" # Open Graph image for social sharing
social:
  type: "Person"
  name: "Leesa Moore"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/leeeeesamo"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lmoore0510"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lmoore0510@gmail.com"

# Analytics
analytics:
  provider: google-gtag
  google:
    tracking_id: "UA-83979019-1"
    anonymize_ip: false

# Author Information
author:
  name: "Leesa Moore"
  avatar: "/assets/images/avatar.jpg" # Path to your profile picture
  bio: "Dynamic and results-driven professional with extensive experience in customer service and IT management."
  location: "Alabama, USA"
  email: "lmoore0510@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/leeeeesamo"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lmoore0510"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lmoore0510@gmail.com"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/leeeeesamo"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/lmoore0510"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lmoore0510@gmail.com"

# SEO Related
google_site_verification: ""
bing_site_verification: ""
naver_site_verification: ""
yandex_site_verification: ""
baidu_site_verification: ""

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules

# Markdown Processing
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Output Settings
permalink: /:categories/:title/
timezone: "America/Chicago"

# Pagination
paginate: 5
paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache 

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
