#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Online Portfolio  
url: 'https://leeeeesamo.github.io/' 

# Change baseurl according to your repository name, or leave disabled for a custom domain
#baseurl: '/online-cv'

# Description for SEO and meta tags
description: Welcome to my online portfolio, where creativity meets professionalism. Explore my work, accomplishments, and career journey through an interactive showcase of my skills, experiences, and achievements. Featuring a detailed resume, comprehensive CV, and highlights of my projects, this portfolio offers a complete view of my professional expertise and aspirations.

# Style settings
theme_skin: ceramic # Choose from blue, turquoise, green, berry, orange, ceramic, teal, oceanstale
chrome_mobile_color: "#00bcd4" # Hex color for Chrome mobile search bar

# Tracker
analytics: UA-83979019-1 # Google Analytics tracking ID

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # Minified output for optimized performance

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false